version: "3.2"
services:
  backend: 
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
  
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    command: npm start
    volumes: 
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  
